In [1]:
include("../LiPoSID.jl")
include("CtrlSID.jl")

using QuantumOptics
basis = NLevelBasis(2)
using LinearAlgebra
using HDF5
using DynamicPolynomials

using Dates
using Statistics

Consider Kossakowski constraints [1] for two-level system (Theorem 3.1 on page 824).

### References

1. **Vittorio Gorini, Andrzej Kossakowski, and E. C. G. Sudarshan (1976)** "Completely positive dynamical semigroups of Nlevel systems" *J. Math. Phys.* 17, 821 (1976) DOI: [10.1063/1.522979](https://doi.org/10.1063/1.522979)

In [2]:
σˣ = [ 0 1 
       1 0 ]

σʸ = [ 0.   im*1
      -im*1 0    ]

σᶻ = [ 1.  0
       0  -1 ] 

fᴷ₁ = σˣ/2; fᴷ₂ = σʸ/2; fᴷ₃ = σᶻ/2

@assert tr(σˣ/2*σʸ/2) == tr(σˣ/2*σᶻ/2) ==  tr(σʸ/2*σᶻ/2) ≈ 0
@assert tr(σˣ/2*σˣ/2) == tr(σʸ/2*σʸ/2) == tr(σᶻ/2*σᶻ/2) ≈ 1/2

fᴼᴺᴮ = [fᴷ₁, fᴷ₂, fᴷ₃]

@polyvar γ[1:3]
@polyvar a[1:3]

Cˢʸᵐᵇ = [ -γ[1]+γ[2]+γ[3]   -im*a[3]          im*a[2]+0.0
           im*a[3]           γ[1]-γ[2]+γ[3]  -im*a[1] 
          -im*a[2]           im*a[1]          γ[1]+γ[2]-γ[3]] 

κ₁ = -γ[1]+γ[2]+γ[3]
κ₂ =  γ[1]-γ[2]+γ[3]
κ₃ =  γ[1]+γ[2]-γ[3]

constr1 = κ₁ + κ₂ + κ₃  
constr2 = κ₁*κ₂ + κ₃*κ₁ + κ₂*κ₃ - a[1]^2 - a[2]^2 - a[3]^2
constr3 = κ₁*κ₂*κ₃ - κ₁*a[1]^2 - κ₂*a[2]^2 - κ₃*a[3]^2 

kossak_constrs = [κ₁, κ₂, κ₃, γ[1], γ[2], γ[3], constr1, constr2, constr3]

@polyvar ϵ h_Re h_Im # h₁ h₂ h₃

Hˢʸᵐᵇ = [ ϵ               h_Re+im*h_Im
           h_Re-im*h_Im   -ϵ            ] / 2

Hᴷˢʸᵐᵇ = h_Re * fᴷ₁ + h_Im * fᴷ₂  + ϵ * fᴷ₃ 

@assert tr(Hᴷˢʸᵐᵇ) == 0
@assert Hᴷˢʸᵐᵇ == Hˢʸᵐᵇ

### Auxilary functions

Fidelity for qubit can be written:

$F(\rho, \sigma) = \operatorname{tr}(\rho \sigma) + 2\sqrt{\det(\rho) \det(\sigma)}$

If we need fidelity more then certain threshold $F$ we have constraint:

$4\det(\rho) \det(\sigma) - F^2 + 2 F \operatorname{tr}(\rho \sigma) - \operatorname{tr}(\rho \sigma)^2 > 0$

It is more convenient to use infidelity therhold $\Delta = 1-F \ll 1$

In [3]:
function infidelity_constr(ρ, σ, Δ) #for two-level system
    F = 1-Δ
    return 4*(det(ρ)*det(σ)) - F^2 + 2*F*tr(ρ*σ) - tr(ρ*σ)^2
end



infidelity_constr (generic function with 1 method)

$4\det(\rho) \det(\sigma) + 2\operatorname{tr}(\rho \sigma)- \operatorname{tr}(\rho \sigma)^2 - 1 > -2\Delta+\Delta^2 +\Delta\operatorname{tr}(\rho \sigma)$

$4\det(\rho) \det(\sigma) + 2\operatorname{tr}(\rho \sigma)- \operatorname{tr}(\rho \sigma)^2 - 1 > \Delta^2 +\Delta(\operatorname{tr}(\rho \sigma) -2)$

$1 - 4\det(\rho) \det(\sigma) - 2\operatorname{tr}(\rho \sigma) + \operatorname{tr}(\rho \sigma)^2 < \Delta(2-\operatorname{tr}(\rho \sigma)) - \Delta^2$



$\frac{1 - 4\det(\rho) \det(\sigma) - 2\operatorname{tr}(\rho \sigma) + \operatorname{tr}(\rho \sigma)^2}
{2-\operatorname{tr}(\rho \sigma)} < \Delta - \frac{\Delta^2}{2-\operatorname{tr}(\rho \sigma)}$

as $\operatorname{tr}(\rho \sigma) \leq 1$ then $2-\operatorname{tr}(\rho \sigma) \in [1,2]$ for $\Delta < 1$:

$\Delta - \frac{\Delta^2}{2-\operatorname{tr}(\rho \sigma)} < \Delta - \Delta^2 < 1$


As $1/x = 1 - (x-1) + (x-1)^2 - (x-1)^3...$  :

$\frac{1 - 4\det(\rho) \det(\sigma) - 2\operatorname{tr}(\rho \sigma) + \operatorname{tr}(\rho \sigma)^2}
{2-\operatorname{tr}(\rho \sigma)} = \left(1 - 4\det(\rho) \det(\sigma) - 2\operatorname{tr}(\rho \sigma) + \operatorname{tr}(\rho \sigma)^2\right)(1-(1-\operatorname{tr}(\rho \sigma))+(1-\operatorname{tr}(\rho \sigma))^2...)$

We can write fown approximate infidelity loss function:

$L(\rho,\sigma)= \left(1 - 4\det(\rho) \det(\sigma) - 2\operatorname{tr}(\rho \sigma) + \operatorname{tr}(\rho \sigma)^2\right)(1-(1-\operatorname{tr}(\rho \sigma)))$

$L(\rho,\sigma)= 1 - 4\det(\rho) \det(\sigma) - 2\operatorname{tr}(\rho \sigma) + \operatorname{tr}(\rho \sigma)^2$

In [4]:
function infidelity_norm(ρ, σ)
    (1-4*(det(ρ)*det(σ))-2*tr(ρ * σ) + tr(ρ * σ)^2)#*(1 -(1-tr(ρ * σ)))#+(1-tr(ρ * σ))^2)#-(1-tr(ρ * σ))^3)
end

infidelity_norm (generic function with 1 method)

Right hand side of the GKSL equation in GKS form:

$\frac{d\rho}{dt} = -i[H,\rho] + \frac{1}{2} \sum_{i,j}^3 C_{ij} \{[f_i, \rho f_j] + [f_i\rho, f_j]\}, \quad \rho \in M(2)$

where $C \succeq 0$ - semidefinite matrix

In [5]:
function Dc(ρ, t)
    U = (Hˢʸᵐᵇ*ρ - ρ*Hˢʸᵐᵇ)/im 
    D = sum(Cˢʸᵐᵇ .* [2*fᵢ*ρ*fⱼ' - ρ*fⱼ'*fᵢ - fⱼ'*fᵢ*ρ  for fᵢ in fᴼᴺᴮ, fⱼ in fᴼᴺᴮ])/2
    return U + D
end 

Dc (generic function with 1 method)

In [6]:
function reassemble_poly(p)
    if isempty(monomials(p))
        p = 0. 
    else
        poly = sum(real(p) * mon for (coef, mon) in zip(coefficients(p), monomials(p)))
    end
    return poly
end

reassemble_poly (generic function with 1 method)

In [7]:
function kossak_infid_obj(ρ, t)

    obj = 0
    for i in 3:length(ρ)
        ρ1 = ρ[i]
        ρ2 = ρ[i-2] + (t[i]-t[i-1])*(Dc(ρ[i],t[i]) + 4*Dc(ρ[i-1],t[i-1]) + Dc(ρ[i-2],t[i-2])) / 3
        obj += infidelity_norm(ρ1,ρ2)#^2
    end

    obj = reassemble_poly(obj)

    return obj

end

kossak_infid_obj (generic function with 1 method)

Read Kurt's spin-boson system data 

In [8]:
function read_timeevolution(file_name, state, γ)
    h5open(file_name, "r") do file
        ρᵧ = read(file[state][string(γ)])
        t = ρᵧ["t"]
        ρ₀₀ = ρᵧ["p0"]; Re_ρ₀₁ = ρᵧ["s_re"];  Im_ρ₀₁ = ρᵧ["s_im"]
        ρ_series = []
        t_series = []

        for i in 1:length(t)
            ρᵢ= [ ρ₀₀[i]                      Re_ρ₀₁[i] + im * Im_ρ₀₁[i]
                  Re_ρ₀₁[i] - im * Im_ρ₀₁[i]  1 - ρ₀₀[i]                 ]
            push!(ρ_series, convert(Matrix{ComplexF64}, ρᵢ))
            push!(t_series, convert(Float64, t[i]))
        end
        return(t_series, ρ_series)
    end
end

function read_GEXY_timeevolution(file_name, γ)

    tᵍ, ρᵍ = read_timeevolution(file_name, "B1", γ)
    tᵉ, ρᵉ = read_timeevolution(file_name, "B2", γ)
    tˣ, ρˣ = read_timeevolution(file_name, "B3", γ)
    tʸ, ρʸ = read_timeevolution(file_name, "B4", γ)

    ρᵍᵉˣʸ = ρᵍ, ρᵉ, ρˣ, ρʸ 
    tᵍᵉˣʸ = tᵍ, tᵉ, tˣ, tʸ

    return tᵍᵉˣʸ , ρᵍᵉˣʸ 

end

read_GEXY_timeevolution (generic function with 1 method)

Assemble objective and constraints using Kossakowski and fidelity constraints

In [9]:
function kossak_GEXY_infid_obj(ρᵍᵉˣʸ, tᵍᵉˣʸ)

    ρᵍ, ρᵉ, ρˣ, ρʸ = ρᵍᵉˣʸ
    tᵍ, tᵉ, tˣ, tʸ = tᵍᵉˣʸ

    polyG = kossak_infid_obj(ρᵍ, tᵍ)
    polyE = kossak_infid_obj(ρᵉ, tᵉ)
    polyX = kossak_infid_obj(ρˣ, tˣ)
    polyY = kossak_infid_obj(ρʸ, tʸ)

    polyGEXY = polyG + polyE + polyX + polyY

    return polyGEXY
end

kossak_GEXY_infid_obj (generic function with 1 method)

Load data

In [10]:
file_name = "../DATA/ALL_GAMMAS_B4_D10.h5"
#γ = [ "0.079477",  "0.25133", "0.79477", "2.5133", "7.9477", "25.133", "79.477", "251.33"]

γᵢ = "0.25133"

tᵍᵉˣʸ , ρᵍᵉˣʸ  = read_GEXY_timeevolution(file_name, γᵢ);

Assemble objective and constraints

In [11]:
polyGEXY = kossak_GEXY_infid_obj(ρᵍᵉˣʸ, tᵍᵉˣʸ)

0.013865878926710245γ₁⁴ + 0.019882917265406433γ₁³γ₂ + 0.0308818499646978γ₁³γ₃ + 0.01354170047776158γ₁³a₁ + 0.013723723853391162γ₁³a₂ + 0.03954713443967658γ₁³a₃ + 0.00965180206911886γ₁³ϵ + 0.013864064157978445γ₁³h_Re + 0.013867342137280476γ₁³h_Im + 0.03378295117161974γ₁²γ₂² + 0.05392666355700118γ₁²γ₂γ₃ + 0.019364346055151943γ₁²γ₂a₁ + 0.019368174470747873γ₁²γ₂a₂ + 0.07126322329208304γ₁²γ₂a₃ + 0.011485112424463201γ₁²γ₂ϵ + 0.019879723574169658γ₁²γ₂h_Re + 0.019885558639089623γ₁²γ₂h_Im + 0.5136584162178857γ₁²γ₃² + 0.030584580939031443γ₁²γ₃a₁ + 0.030714184866620406γ₁²γ₃a₂ + 1.0609175467980256γ₁²γ₃a₃ + 0.02090617197355523γ₁²γ₃ϵ + 0.030883733656697242γ₁²γ₃h_Re + 0.030879169445285272γ₁²γ₃h_Im + 0.12214213992969394γ₁²a₁² + 0.013138987152853191γ₁²a₁a₂ + 0.03923850456229251γ₁²a₁a₃ + 0.0094230246290185γ₁²a₁ϵ + 0.017889822483360886γ₁²a₁h_Re + 0.0896131185782428γ₁²a₁h_Im + 0.12234346858528543γ₁²a₂² + 0.039383995845216596γ₁²a₂a₃ + 0.009582265192861459γ₁²a₂ϵ - 0.06234833442299548γ₁²a₂h_Re + 0.0180709010

In [12]:
polyGEXY = kossak_GEXY_infid_obj(ρᵍᵉˣʸ, tᵍᵉˣʸ)

0.013865878926710245γ₁⁴ + 0.019882917265406433γ₁³γ₂ + 0.0308818499646978γ₁³γ₃ + 0.01354170047776158γ₁³a₁ + 0.013723723853391162γ₁³a₂ + 0.03954713443967658γ₁³a₃ + 0.00965180206911886γ₁³ϵ + 0.013864064157978445γ₁³h_Re + 0.013867342137280476γ₁³h_Im + 0.03378295117161974γ₁²γ₂² + 0.05392666355700118γ₁²γ₂γ₃ + 0.019364346055151943γ₁²γ₂a₁ + 0.019368174470747873γ₁²γ₂a₂ + 0.07126322329208304γ₁²γ₂a₃ + 0.011485112424463201γ₁²γ₂ϵ + 0.019879723574169658γ₁²γ₂h_Re + 0.019885558639089623γ₁²γ₂h_Im + 0.5136584162178857γ₁²γ₃² + 0.030584580939031443γ₁²γ₃a₁ + 0.030714184866620406γ₁²γ₃a₂ + 1.0609175467980256γ₁²γ₃a₃ + 0.02090617197355523γ₁²γ₃ϵ + 0.030883733656697242γ₁²γ₃h_Re + 0.030879169445285272γ₁²γ₃h_Im + 0.12214213992969394γ₁²a₁² + 0.013138987152853191γ₁²a₁a₂ + 0.03923850456229251γ₁²a₁a₃ + 0.0094230246290185γ₁²a₁ϵ + 0.017889822483360886γ₁²a₁h_Re + 0.0896131185782428γ₁²a₁h_Im + 0.12234346858528543γ₁²a₂² + 0.039383995845216596γ₁²a₂a₃ + 0.009582265192861459γ₁²a₂ϵ - 0.06234833442299548γ₁²a₂h_Re + 0.0180709010

In [13]:
@show minimum(abs.(coefficients(polyGEXY)))
@show maximum(abs.(coefficients(polyGEXY)))
maxdegree(polyGEXY)

minimum(abs.(coefficients(polyGEXY))) = 6.344791442749598e-5
maximum(abs.(coefficients(polyGEXY))) = 7.522412762986921


4

Optimization

In [14]:
using TSSOS

In [15]:
vars = variables(polyGEXY)
opt,sol,data = cs_tssos_first([polyGEXY, kossak_constrs...], vars, 3, solution=true)#, mosek_setting=settings)

*********************************** TSSOS ***********************************
TSSOS is launching...
-----------------------------------------------------------------------------
The clique sizes of varibles:
[9]
[1]
-----------------------------------------------------------------------------
Obtained the variable cliques in 0.091079189 seconds. The maximal size of cliques is 9.
Starting to compute the block structure...
Obtained the block structure in 0.795601041 seconds.
The maximal size of blocks is 220.
Assembling the SDP...
There are 5005 affine constraints.
SDP assembling time: 2.480272056 seconds.
Solving the SDP...
Problem
  Name                   :                 
  Objective sense        : maximize        
  Type                   : CONIC (conic optimization problem)
  Constraints            : 5005            
  Affine conic cons.     : 0               
  Disjunctive cons.      : 0               
  Cones                  : 0               
  Scalar variables       : 1       

(0.059630337674693897, [0.09784466131991955, 0.1647586300230335, 0.26246529123711304, 1.7358556069545041e-6, -2.060348297228756e-6, -0.2539350308261225, 25.144798243296954, 0.0003351324097369164, -0.0003540368472531925], TSSOS.mcpop_data(9, 0, 9, 0, Vector{Vector{UInt16}}[[[], [0x0001], [0x0001, 0x0001], [0x0001, 0x0001, 0x0001], [0x0001, 0x0001, 0x0001, 0x0001], [0x0001, 0x0001, 0x0001, 0x0002], [0x0001, 0x0001, 0x0001, 0x0003], [0x0001, 0x0001, 0x0001, 0x0004], [0x0001, 0x0001, 0x0001, 0x0005], [0x0001, 0x0001, 0x0001, 0x0006]  …  [0x0008, 0x0008, 0x0008, 0x0009], [0x0008, 0x0008, 0x0009], [0x0008, 0x0008, 0x0009, 0x0009], [0x0008, 0x0009], [0x0008, 0x0009, 0x0009], [0x0008, 0x0009, 0x0009, 0x0009], [0x0009], [0x0009, 0x0009], [0x0009, 0x0009, 0x0009], [0x0009, 0x0009, 0x0009, 0x0009]], [[0x0001], [0x0002], [0x0003]], [[0x0001], [0x0002], [0x0003]], [[0x0001], [0x0002], [0x0003]], [[0x0001]], [[0x0002]], [[0x0003]], [[0x0001], [0x0002], [0x0003]], [[0x0001, 0x0001], [0x0001, 0x0002],

In [16]:
solution = variables(polyGEXY) => sol

Cˢⁱᵈ = subs(Cˢʸᵐᵇ, solution)
Hˢⁱᵈ = subs(Hˢʸᵐᵇ, solution)

Cˢⁱᵈ[1:2, 1:2]

2×2 Matrix{Polynomial{true, ComplexF64}}:
 (0.329379+0.0im)   (-0.0+0.253935im)
 (-0.0-0.253935im)  (0.195551+0.0im)

In [17]:
Hˢⁱᵈ

2×2 Matrix{Polynomial{true, ComplexF64}}:
 (12.5724+0.0im)              (0.000167566-0.000177018im)
 (0.000167566+0.000177018im)  (-12.5724+0.0im)

In [18]:
Hˢⁱᵈ = convert.(ComplexF64,Hˢⁱᵈ)
Cˢⁱᵈ = convert.(ComplexF64,Cˢⁱᵈ)

3×3 Matrix{ComplexF64}:
 0.329379+0.0im              0.0+0.253935im         0.0-2.06035e-6im
      0.0-0.253935im    0.195551+0.0im              0.0-1.73586e-6im
      0.0+2.06035e-6im       0.0+1.73586e-6im  0.000138+0.0im

In [19]:
function get_lindblad_operators(C::Matrix{ComplexF64}, basis_ops::Vector{Matrix{ComplexF64}})
    # Check that C is a square matrix and basis_ops has the same dimension
    n = size(C, 1)
    if size(C, 2) != n || length(basis_ops) != n
        throw(ArgumentError("Dimensions of C and basis_ops do not match"))
    end

    # Perform eigenvalue decomposition of C
    eigvals, eigvecs = eigen(C)

    # Construct the Lindblad operators
    lindblad_ops = []
    for i in 1:n
        if eigvals[i] > 1e-10  # Filter out negligible eigenvalues to ensure numerical stability
            lindblad_op = zeros(ComplexF64, size(basis_ops[1]))
            for j in 1:n
                lindblad_op .+= sqrt(eigvals[i]) * eigvecs[j, i] * basis_ops[j]
            end
            push!(lindblad_ops, lindblad_op)
        end
    end

    return lindblad_ops
end

effective_Lindblad = get_lindblad_operators(Cˢⁱᵈ, fᴼᴺᴮ)

2-element Vector{Any}:
 ComplexF64[0.005873806017001783 + 0.0im 5.299825184064286e-6 + 4.88849136050628e-6im; -4.104219374806926e-5 - 3.753538762731577e-5im -0.005873806017001783 + 0.0im]
 ComplexF64[-1.3429806674026688e-6 + 0.0im -0.27670542894889516 + 0.4261870543310784im; -0.03584527665469264 + 0.055209588516506175im 1.3429806674026688e-6 + 0.0im]

In [20]:
ρᵍ₀ = [ 1 0.
        0 0 ]    # state to measure initial distance from

dodeca_10_states = ["D"*string(n) for n=1:10];

basis_states = ["B"*string(n) for n=1:4];

train_states = basis_states 
test_states = dodeca_10_states;

In [21]:
FminStates = []
FmedianStates = []
FmeanStates = []

for state in test_states # loop over initial states
    
    print(state*" ")

    start_time = time()

    tₛ, ρₛ = read_timeevolution(file_name, state, γᵢ)
    ρₛ = convert(Vector{Matrix{ComplexF64}}, ρₛ)
    #bᵗˢᵗ = LiPoSID.bloch(ρₛ)
    ρᵗˢᵗ = [DenseOperator(basis,Hermitian(ρₜ)) for ρₜ in ρₛ]
    tᵗˢᵗ = convert.(Float64, tₛ)

    #Simulated LME 
    #tˢⁱᵐ, ρˢⁱᵐ  = timeevolution.master(tᵗˢᵗ, ρᵗˢᵗ[1], DenseOperator(basis, Hˢⁱᵈ), [Jˢⁱᵐ])
    #bˢⁱᵐ = LiPoSID.bloch([ρᵢ.data for ρᵢ in ρˢⁱᵐ])

    ρₒ = DenseOperator(basis,ρₛ[1])
    dt = tᵗˢᵗ[2] - tᵗˢᵗ[1]
    tᵉⁿᵈ = tᵗˢᵗ[end]

    #print("effective_Lindblad_ops for Kossakowski")

    
    effective_Lindblad_ops = [DenseOperator(basis,j) for j in effective_Lindblad]

    #print("Simulating Kossakowski")

    tout, ρ_t_kossak = timeevolution.master(tᵗˢᵗ, ρₒ, DenseOperator(basis, Hˢⁱᵈ), effective_Lindblad_ops)
    ρˢⁱᵈ  = [ρₜ.data for ρₜ in ρ_t_kossak]

    #print("Calculating Fidelity")

    #F = LiPoSID.fidelity_series(basis, [ρₜ.data for ρₜ in ρˢⁱᵐ], ρˢⁱᵈ)
    F = LiPoSID.fidelity_series(basis, ρₛ, ρˢⁱᵈ)
    
    FminState = minimum(F)
    FmedianState = median(F)
    FmeanState = mean(F)
    
    push!(FminStates, FminState)
    push!(FmedianStates, FmedianState)
    push!(FmeanStates, FmeanState)

end

# Calculate the mean
F_mean_value = mean(FmeanStates)

# Calculate the median
F_median_value = median(FmedianStates)

# Calculate the min
F_min_value = minimum(FminStates)

println()
println("Mimimal fidelity for "*γᵢ*": ", F_min_value)
println("Median fidelity for "*γᵢ*": ", F_median_value)

D1 D2 D3 D4 D5 D6 D7 D8 D9 D10 
Mimimal fidelity for 0.25133: 0.9959004588831878
Median fidelity for 0.25133: 0.9984956115791352
